# Generated by Django 2.0.2 on 2018-03-17 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='coment_text',
            new_name='comment_text',
        ),
    ]
