# Generated by Django 2.0.2 on 2018-03-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='picture',
            field=models.ImageField(default='/home/pavel/Repositories/BookShelfSite/book_shelf/files/media/pictures/book_covers/defaultCover.jpg', upload_to='pictures/book_covers/'),
        ),
    ]
