# Generated by Django 2.0.2 on 2018-03-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20180317_1439'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='main_app_bo_title_d3a542_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['created_at'], name='main_app_bo_created_0d7977_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['from_user', 'content_type', 'object_id', 'created_at'], name='main_app_co_from_us_4d8ff9_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['created_at'], name='main_app_no_created_6fdbaf_idx'),
        ),
    ]
